-- 코드를 입력하세요
SELECT A.PRODUCT_ID,A.PRODUCT_NAME,SUM(AMOUNT)*PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A RIGHT OUTER JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE MONTH(B.PRODUCE_DATE) = 05 AND YEAR(B.PRODUCE_DATE)=2022
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID