-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A INNER JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (SEX_UPON_INTAKE = 'Intact Male' AND SEX_UPON_OUTCOME = 'Neutered Male') or (SEX_UPON_INTAKE = 'Intact Female' AND SEX_UPON_OUTCOME = 'Spayed Female')
ORDER BY A.ANIMAL_ID
