-- 코드를 입력하세요
SELECT FLAVOR
FROM(
SELECT A.FLAVOR, (SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER)) AS TOTAL_ORDER
FROM FIRST_HALF AS A JOIN JULY AS B 
ON A.FLAVOR = B.FLAVOR

GROUP BY A.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3
)ASDF